### ISSUE TITLE
Snippet: XYPlot

### ISSUE THREAD

**Issue by kmugEq** [equinor/vscode-septic#1]
Se under for mitt forsøk på å lage en XYPlot snippet.

{
  "XYPlot": {
    "prefix": "XYPlot",
    "body": [
      "XYPlot:        KompAMap\r",
      "           Row=  1\r",
      "           Col=  1\r",
      "       RowSize=  1\r",
      "       ColSize=  1\r",
      "         Title=  \"Example: compressor chart\"\r",
      "        Legend=  OFF\r",
      "     SpanScale=  OFF\r",
      "        xTitle=  \"Flow[0-100%]\"\r",
      "        yTitle=  \"Pd/Ps-1 [%]\"\r",
      "          xMin=  0\r",
      "          xMax=  100\r",
      "          yMin=  0\r",
      "          yMax=  100\r",
      "         xSpan=  100\r",
      "         ySpan=  100\r",
      "\r",
      "  Curve:         surge\r",
      "         Color=  \"RED\"\r",
      "          Text=  \"Surge\"\r",
      "         Width=  2\r",
      "       xPoints=  26\r",
      "             0          1.54          3.07          4.61          6.14\r",
      "          7.68          9.22         10.75         12.29         13.83\r",
      "         15.36          16.9         18.43         19.97         21.51\r",
      "         23.04         24.58         26.12         27.65         29.19\r",
      "         30.72         30.72         35.57         41.08         48.27\r",
      "         53.36\r",
      "       yPoints=  26\r",
      "             0          0.08          0.32          0.71          1.27\r",
      "          1.98          2.85          3.88          5.07          6.42\r",
      "          7.93          9.59         11.42          13.4         15.54\r",
      "         17.84         20.29         22.91         25.69         28.62\r",
      "         31.71         31.71         44.38         60.96         80.87\r",
      "         92.09\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         Kontrollinje\r",
      "         Color=  \"Orange\"\r",
      "          Text=  \"Kontrollinje\"\r",
      "         Width=  2\r",
      "       xPoints=  6\r",
      "          18.7          33.8         39.13         45.19          53.1\r",
      "          58.7\r",
      "       yPoints=  6\r",
      "             0         31.71         44.38         60.96         80.87\r",
      "         92.09\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         c2\r",
      "         Color=  \"Brown\"\r",
      "          Text=  \"Stonewall\"\r",
      "         Width=  2\r",
      "       xPoints=  3\r",
      "            17            74            90\r",
      "       yPoints=  3\r",
      "             0         35.63         61.67\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         speed105\r",
      "         Color=  \"Gray\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "       xPoints=  5\r",
      "         53.36         62.47         71.57         80.67         87.95\r",
      "\r",
      "       yPoints=  5\r",
      "         92.09         87.03         79.45         69.26         59.62\r",
      "\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         speed100\r",
      "         Color=  \"Gray\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "       xPoints=  5\r",
      "         48.27         57.66         67.04         76.43         83.94\r",
      "\r",
      "       yPoints=  5\r",
      "         80.87         76.42         69.27         59.74         50.47\r",
      "\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         speed90\r",
      "         Color=  \"Gray\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "       xPoints=  5\r",
      "         41.08         49.97         58.85         67.73         74.84\r",
      "\r",
      "       yPoints=  5\r",
      "         60.96         57.29         51.51         44.05         37.02\r",
      "\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         speed80\r",
      "         Color=  \"Gray\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "       xPoints=  5\r",
      "         35.57         42.47         49.38         56.28          61.8\r",
      "\r",
      "       yPoints=  5\r",
      "         44.38          41.9         38.19          33.5         29.04\r",
      "\r",
      "         Style=  Solid\r",
      "\r",
      "  Curve:         speed70\r",
      "         Color=  \"Gray\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "       xPoints=  5\r",
      "         30.72         36.04         41.37         46.69         50.94\r",
      "\r",
      "       yPoints=  5\r",
      "         31.71         30.02         27.69         24.81         22.14\r",
      "\r",
      "         Style=  Solid\r",
      "\r",
      "  DynPoint:      P1\r",
      "         Color=  \"BLUE\"\r",
      "          Text=  \"\"\r",
      "         Width=  1\r",
      "      HistSize=  -1\r",
      "          xXvr=  \"35UIC3601PV\"\r",
      "          yXvr=  \"35UIC3601RTO\""
    ],
    "description": "XYplot for compressor charts etc."
  }
}

**Comment by einarsi** [comment]
La til en drøss med snippets i 8c7aac2670f08096a27271a8eff5d0666b271163, inkl default XYPlot.
