### ISSUE TITLE
Erroneous reporting of non-existing Xvrs

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#109]
Looks like the regex for parsing Xvr names in calcs needs to be fixed. J1Zpc is the name of the Xvr, MaxUp is a property/attribute of the Xvr:
![image](https://user-images.githubusercontent.com/2356425/235645527-860ee635-a494-447c-84e1-62d9604fd512.png)
Also check spelling in error message: "that *doesn´t* exist"
Or preferably: "Reference to undefined Xvr"

**Comment by vetlek** [comment]
This issue will be fixed in #106
