### ISSUE TITLE
Syntax highlighting for one liners

### ISSUE THREAD

**Issue by vetlek** [equinor/vscode-septic#113]
Syntax highlighting for Alg (and other attributes) in CalcPvr (and other objects) contained on a single line is not working.   Works when the Alg (and other attributes) is on a new line.

One line: 
![image](https://user-images.githubusercontent.com/89847536/235692993-2bbbffa5-dd3a-4fd9-8540-4d2f20092d8e.png)

Multiple lines:
![image](https://user-images.githubusercontent.com/89847536/235693583-6f223c29-ec44-4971-b887-b9fbe90488c9.png)

**Comment by einarsi** [comment]
Ditto for autocompletion in current main.
