### ISSUE TITLE
Calc argument checking

### ISSUE THREAD

**Issue by mortenfre** [equinor/vscode-septic#124]
Undersøk doxygen \param kan utnyttes til å strukturere slik at vscode kan hente dette opp til videre bruk.
https://www.doxygen.nl/manual/docblocks.html har info

```
/*!
  \class CalcSpIvOn

  Intended for Mvr/Cvr only, turns ON/OFF Cvr.SetPnt or Mvr.Iv<br>

  Alg= spivon(TAG,MODE)<br>
  TAG: Cvr or Mvr Id<br>
  MODE: OFF/ON = 0/1<br>

  If MODE is not exactly 0 or 1, no action is performed. The quality of MODE does not matter.<br>

  Note: spivon acts directly on the actual TAG, caution if used in an if() context.

  V = 1/0 for ON/OFF (indicator only for what has been set)
  Q = GOOD means that ON/OFF has been set, Q = BAD means that nothing has been done to the TAG.
*/
```

**Comment by vetlek** [comment]
Det bør fungere å bruke `\param` + noe tilpasset informasjon for dokumentere funksjonene tilstrekkelig til å støtte argument checking.

Tanker om tilpasset informasjon for hver param:

Direction: 
[in] - Parametere brukes kun til input
[out] - Parameteren blir skrevet til f.eks for setMaxDn

Cardinality:
[+] - En eller flere
[1+] - Partall antall
[2+] - Oddetall 
[n] - N antall
[ref other param] - Antall skal matche verdien til en annen \param

Default [] vil være enkelt argument. Vet ikke om all trengs, men hørt rykter om at både odd og partall antall er en greie. 

Type:
[obj1, obj2] - Beskriver om parameteren skal være et spesielt type objekt i.e. Xvr (Mvr etc) eller System (DmmyAppl etc).
Default [] er at man forventer et tall. Finnes det andre datatyper som kreves av calcer?

Kan se for meg at en param vil se slik ut:

\param [dir] [cardinality] [type] name

**Comment by vetlek** [comment]
I tillegg bør det være en markør i starten av doxygen dokumentasjonen for hver calc som identifiserer dette som en calc + navnet som man skal bruke i config filene.

**Comment by vetlek** [comment]
Forslag for intpolType1: 

/*!
  \class CalcIntpolType1

  \fn intpoltype1(x,X1,Y1,X2,Y2,...,XN,YN)
  
  \brief Function calculates y by linear interpolation of the X,Y pairs.
  Assumes that the sequence of X1, X2, ..., XN values are monotonically increasing.
  An input value x < X1 will give y = Y1, and x > XN gives y = YN.

  \param[in] x Actual x-value (Float,Xvr)
  \param[in] NN Values defining the curve to be interpolated. Values comes in X,Y-pairs. (Float) [2+]
  
  \return Interpolated value (Float)

  \par Output value and quality:
    - Q = GOOD only if ALL arguments are GOOD and an odd number (5,7,9 ...) of parameters are specified, else Q = BAD
    - V = 0 when Q = BAD, Y1 when x <= X1, YN when x >= XN, Y(n-1) + (x - X(n-1))*(Y(n)-Y(n-1))/(X(n)-X(n-1)) when X(n-1)<= x <= X(n)
*/

Parametere vil ha den generelle formen:

\param[dir(in, out)] Navn Beskrivelse (Datatype(int, float, xvr, etc.)) [antall(n, +, 1+ , 2+)]
