### ISSUE TITLE
Scientific notation is valid for numbers

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#125]
![image](https://user-images.githubusercontent.com/2356425/236193165-42b1fdc8-3c1d-4ae6-bba6-9f2d0393eeaf.png)

-1e1 is a valid number for calcs (Alg). 

@mortenfre : Can scientific notation be used anywhere numbers are used (limits, setpoints etc)?

**Comment by einarsi** [comment]
This may be an invalid issue. Horses should be held.

**Comment by vetlek** [comment]
Closing stale issue. Reopen if still relevant.
