### ISSUE TITLE
Invalid jinja

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#126]
![image](https://user-images.githubusercontent.com/44671818/236231098-cffcdaf1-1128-460c-ac3d-4a9d7c45f0c4.png)

**Comment by palkitt** [comment]
Funker for meg...

**Comment by vetlek** [comment]
Jinja expressions are currently not supported in algs. The error message should be updated to clarify that the jinja expression might be valid, but parsing of the alg is not supported when using jinja expression. Might support algs containing jinja expressions at a later stage, but will not prioritize it now.
