### ISSUE TITLE
Missing identifier marked on valid separator construction

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#148]
![image](https://github.com/equinor/septic-config-generator/assets/44671818/1c30ac08-3101-4d67-a56c-4b6aef07425f)

**Comment by einarsi** [comment]
@vetlek : It is quite common to use asterisks like @palkitt is showing. The intention is to act as a visible separator between segments of calcs that belong together. Although the name is not proper, it is still accepted by SEPTIC.

These ad-hoc separators may contain text as part of the CalcPvr name, similar to what is shown in Text1 above.
