### ISSUE TITLE
Undefined variable marked on application names 

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#150]
setappldesmode(), getappldesmode() take application as arguments and not XVRs
![image](https://github.com/equinor/septic-config-generator/assets/44671818/111caa10-e0c6-4b34-bf2b-a4ef24ea0cbd)

**Comment by einarsi** [comment]
@palkitt and @mortenfre : 
- Are these the only two calcs that take application name as argument? 
- Which, if any, other applications apart from SmpcAppl and DmmyAppl are relevant for these calcs (not including the upcoming and as-of-yet-unnamed new MPC application)?
- Are there any other calcs that can take other object types as argument (not Xvr or appl)?
