### ISSUE TITLE
Lack of log info when server crashes

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#157]
Not sure exactly what I did, but it happened while I was rewriting some CalcPvrs from single-line to regular block format. 
![image](https://github.com/equinor/vscode-septic/assets/2356425/90af73f2-ebe2-4043-a316-152919fd6b50)
![image](https://github.com/equinor/vscode-septic/assets/2356425/0eb7ef5c-0177-4c00-abec-7f5f6774974e)

The error output doesn't really give much to go on, and I am so far not able to reproduce it. 
I suggest to add more debug information to the output in case/when this happens again.

**Comment by vetlek** [comment]
Close until problems reoccur
