### ISSUE TITLE
Missing variable diagnostics on pure jinja in calcs

### ISSUE THREAD

**Issue by vetlek** [equinor/vscode-septic#176]
Warnings for Undefined Xvr is given for jinja expressions i.e `{{ Something}}` which might be valid. Should consider accepting pure jinja variables without any warning or give a recommended practice of first assigning the value to an Evr before using it in a calc.

 
![image](https://github.com/equinor/vscode-septic/assets/89847536/2924c31a-cee5-44f1-95fa-eedb9e235298)

**Comment by einarsi** [comment]
Pure jinja expressions or variables must be accepted as valid.
