### ISSUE TITLE
Warning when CalcPvr/Evr is used in Alg without setgood()

### ISSUE THREAD

**Issue by mortenfre** [equinor/vscode-septic#194]
![image](https://github.com/equinor/vscode-septic/assets/64948076/f94b6698-c37a-4c8b-9fc3-f068715c5952)

When a CalcPvr/Evr is part of the Alg you're in danger of beeing BAD forever if one of the other inputs go BAD in one sample.

This can be fixed by using setgood(EVR_ID) in the Alg. forgetting this can possibly be flagged with a warning in vscode? 
```
CalcPvr: 13PI5113_test Alg= filt(if(13FV5114>FV5104filtergrense, 13PI5113, 13PI5113_test), 20)
```
should give warning 
```
CalcPvr: 13PI5113_test Alg= filt(if(13FV5114>FV5104filtergrense, 13PI5113, setgood(13PI5113_test)), 20)
```
is ok

**Comment by vetlek** [comment]
Closed by #536
