### ISSUE TITLE
Instruction: # missing in {# format:off}

### ISSUE THREAD

**Issue by AdamZalewski** [equinor/vscode-septic#212]
In a text within Instructions:

Formatting of cnfg files can be enabled by setting septic.formatting.enabled = True in the settings. Comments // or /* */ and jinja-comments {#   #} are not formatted. Everything between the jinja expressions {% for w %} ... {% endfor %} and {% if %} ... {% endif %} are not formatted. To avoid formatting certain sections of the file the flags {# format:off} and {# format:on #} can be used to turn off and on again formatting (Tip: snippets available by writting formaton/off).

{# format:off} should be {# format:off #}

**Comment by einarsi** [comment]
@AdamZalewski : Looks like a great candidate for an issue to fix yourself - just open a PR with the suggested change (which can be done here at GitHub, if you prefer) :)

**Comment by vetlek** [comment]
Closed by #209
