### ISSUE TITLE
Autoformat should leave Jinja labels untouched

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#219]
Example: Identifiers such as 
```
  SopcMvr:       {{ Wellname }}Zgl
```
are autoformatted:
```
  SopcMvr:       {{Wellname}}Zgl
```
while for instance
```
         Text2= "FY-18-{{ WellNo }}001"
```
is not touched.

Suggest to always leave Jinja labels untouched. I like my spaces :)

**Comment by vetlek** [comment]
Should be closed by #221
