### ISSUE TITLE
*** gives error Identifier contains the following invalid chars: *

### ISSUE THREAD

**Issue by kmugEq** [equinor/vscode-septic#254]
It is common in the septic team to group calcs using *** to separate.

![image](https://github.com/equinor/vscode-septic/assets/44665004/bda06dfc-6386-44cd-a971-405b9268e561)
![image](https://github.com/equinor/vscode-septic/assets/44665004/9b7d2bff-fef7-4323-b136-5e11173b35da)

**Comment by vetlek** [comment]
It was decided in a previous issue #148 (but not documented in the issue) that using * to divide the calcs should not be used. The preferred method is to use underscores (_) instead of * and the divider should contain a description of the calcs it groups.

**Comment by kmugEq** [comment]
LGTM
