### ISSUE TITLE
Error notice in calc that seems correct

### ISSUE THREAD

**Issue by John-Morten** [equinor/vscode-septic#256]
CalcPvr:       ExportChokeModel
         Text1=  "Choke process setpoint from CA block"
         Text2=  "Deadband i prosess 0.5 bar, modellgain ca 1/3 choke/innløpstrykk."
           Alg=  "setmeas(EXPZPC_Y, if(and (EXPZPC_XAPC>0.5, abs(EXPZPC_YX-EXPZPC_XOUT)>0.5), min(max(filt(EXPZPC_Y+3*InletPressure_Deviation+0.01*PIC_Integral,0.1),0),100),EXPZPC_Y))"

![image](https://github.com/equinor/vscode-septic/assets/21998408/56320296-0add-45cb-9eb9-e37b03964f3c)

Missing closing paranthesis at end of grouping.septic(E201)

**Comment by vetlek** [comment]
You have a space here `...if(and (.... ` which causes the error

**Comment by vetlek** [comment]
The error message could be improved, so reopening
