### ISSUE TITLE
Search for calcs based on keyword/topic

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#273]
Sometimes we may not recall exactly what a calc is called, or we may wonder which calcs exist that are related to a specific topic. We therefore wish some kind of functionality to search for calcs based on keywords. 

One suggestion is to extend the already planned/semi-implemented auto-completion of calc names: The list of direct completion suggestions can be extended with calcs that contain the keyword that is being typed (would require minimum length of typed keyword before searching).

Are there better alternatives in VS Code you know of that can be used? Perhaps a command to initiate the search? ctrl-shift-P -> "SEPTIC: Search for calc" -> Pops up dialog box or something like that.

**Comment by vetlek** [comment]
You can select the text the autocomplete is going to search. The filtering is done on the client side, so don't know if we can change some settings to customize the client. The other option is to create a command that display a search tab and results. The command might be harder to implement and I don't know how we can display the results.
