### ISSUE TITLE
Inconsistent autoformatting of Xvrs list

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#288]
Before on the left, after on the right (no change, but there should be two spaces between elements)
![image](https://github.com/equinor/vscode-septic/assets/2356425/2ad98097-839e-4ed9-b21d-d859a34d6f37)
Here it works as intended:
![image](https://github.com/equinor/vscode-septic/assets/2356425/3033bdf6-3cf6-43b8-89a4-130fa66f5728)

**Comment by einarsi** [comment]
Inside for-loop

**Comment by vetlek** [comment]
Closing this issue since the described behavior is expected. Create new issue related to turning on formatting inside for loops etc. if relevant.
