### ISSUE TITLE
Diagnostics for bad operators

### ISSUE THREAD

**Issue by John-Morten** [equinor/vscode-septic#328]
Legal operators in calcs are +, -, *, /, <, >,>=,<=,==
Illegal operators should be warned, e.g ++, **, !=, <>, !, etc

**Comment by vetlek** [comment]
Already implemented. Closing issue.

**Comment by John-Morten** [comment]
Thanks! 
I see "1+++1" is marked, while "1---1" is not. 
Same "1/+1" is illegal, while ""1/-1" is ok
Do we have a legal operator for not equal? != or <> are illegal
