### ISSUE TITLE
Diagnostic struggling with jinja

### ISSUE THREAD

**Issue by kmugEq** [equinor/vscode-septic#369]
Diagnostic struggling with jinja, i believe?

https://github.com/equinor/septic-TrollA/blob/161abac215a9781b96c0afdfd3b6f47072f01c8b/Sim/SCG/01_TRAAPOTemplates/036_DmmyApplPostWell.cnfg#L21

![image](https://github.com/equinor/vscode-septic/assets/44665004/681a16d2-f1f1-41ff-bff0-36870ae314f4)

**Comment by vetlek** [comment]
This issue is an edge case that is not going to be handled. Suggest checking if you can use ``` instead of `"` in the jinja.
