### ISSUE TITLE
Invalid parent of type object Curve

### ISSUE THREAD

**Issue by kmugEq** [equinor/vscode-septic#370]
![image](https://github.com/equinor/vscode-septic/assets/44665004/11565272-3198-4063-bbdf-2059358fc351)

https://github.com/equinor/septic-TrollA/blob/161abac215a9781b96c0afdfd3b6f47072f01c8b/Sim/SCG/01_TRAAPOTemplates/067_DspKomprKart.cnfg#L135

**Comment by vetlek** [comment]
Documentation issues should be reported on the SEPTIC repo
