### ISSUE TITLE
Last part of file deleted upon saving

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#457]
With the following contents, the last part (below "Group 2") is removed on saving:
```
// Group 1
Name ="opctag1.a"
Name ="opctag1.b"

// Group 2
Name ="opctag1.c"
Name ="opctag1.d"
```

**Comment by vetlek** [comment]
This happens when .cnfg format is used for things that are not Septic code. Can be fixed by putting a formatoff at the beginning (might need the format on at the end). Closing issue since it is "misuse" of .cnfg and is an edge case.
