### ISSUE TITLE
Bug with length of variables in list

### ISSUE THREAD

**Issue by vetlek** [equinor/vscode-septic#465]
Variables in list are clipped such that the first and last char is missing when attempting to rename.

![image](https://github.com/equinor/vscode-septic/assets/89847536/2f53fc18-aee1-4edf-93ab-a7b165755ac5)

**Comment by einarsi** [comment]
When attempting to rename what, exactly? What is missing from the screenshot? Hyphens around all the {{ Wellname }}nnn names?

**Comment by vetlek** [comment]
The first and last char of variables without hyphens are not updated when renaming a variable, such that you would get ?`{{{Wellname}}NewNamee` when renaming `{{Wellname}}Name`
