### ISSUE TITLE
Auto-generate snippets based on version setting

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#503]
Snippets change over time and do not retain compatibility with older versions. It is somewhat cumbersome to maintain multiple version-specific snippets for objects. Can snippets instead be autogenerated based on keywords found in object documentation? 

This has two nice benefits:
- No need to maintain documentation and snippets separately
- Snippets will be available for all documented objects, not just those we create manually

We can even consider adding more keywords to the documentation so that multiple snippets can be autogenerated for one object type, e.g. a brief snippet for Evrs, snippets including only linear properties or also nonlinear properties for Mvrs etc.

**Comment by vetlek** [comment]
I guess we can revisit the tag concept that was discussed when we were specing the documentation

**Comment by vetlek** [comment]
Can be dynamically selected based on version using code completion. Version specific snippets are provided as code completion, while the common snippets are kept in the file.  Can add a file in each version with pre-generated snippets based on the object documentation, that are loaded based on the current selected version similar to what is already done for the documentation of calcs and objects.
