### ISSUE TITLE
Formatter removes Jinja variables following Jinja expressions 

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#514]
![image](https://github.com/equinor/vscode-septic/assets/2356425/d105472c-92f5-4639-b0ec-bfda9dfc78d6)

Formats to
![image](https://github.com/equinor/vscode-septic/assets/2356425/43d65287-4c58-4305-9bb1-5ac016686dda)

Using v1.16.4

**Comment by vetlek** [comment]
The usage here (jinja etc before the definition of the first object in the file) is an edge case and we can`t expect the extension to handle all these cases. Using comments is an option in cases like this. Closing.
