### ISSUE TITLE
No warning of duplicate definitions of XVRs

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#538]
No warning or error is indicated in case of duplicate definitions of XVRs. This seems to be OK with SEPTIC, but could preferably give a warning in VSCode. 

![image](https://github.com/equinor/vscode-septic/assets/44671818/2c16ad98-f5aa-4037-b216-a6b8ae18bc40)

**Comment by John-Morten** [comment]
Similar: no warning with duplicate fields, e.g. 2x Meas in an Evr definition

**Comment by vetlek** [comment]
> Similar: no warning with duplicate fields, e.g. 2x Meas in an Evr definition

Created a separate issue for this #563
